"""
Django settings for web_django project.
Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path
import os
import dj_database_url

# Đường dẫn gốc của dự án
BASE_DIR = Path(__file__).resolve().parent.parent

# Mã bảo mật và chế độ gỡ lỗi
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-f3)14(%h0sn7=(^m9s^vwjb)_tq8!p&#0$fihjrr2736ik6u7k')
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',')

# Danh sách các ứng dụng và thư viện được cài đặt
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize', 
    'app', 
]

# Các lớp trung gian xử lý bảo mật và phiên làm việc
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'web_django.urls'

# Cấu hình giao diện (Template) và các hàm xử lý dữ liệu chung
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.netcafe_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'web_django.wsgi.application'

# Cấu hình cơ sở dữ liệu (đang dùng SQLite)
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}

# Các quy tắc kiểm tra độ mạnh của mật khẩu
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- CẤU HÌNH NGÔN NGỮ & ĐỊNH DẠNG TIỀN TỆ ---
LANGUAGE_CODE = 'vi-vn' # Tiếng Việt
TIME_ZONE = 'Asia/Ho_Chi_Minh' # Múi giờ Việt Nam
USE_I18N = True
USE_TZ = True

# Thiết lập dấu chấm (.) phân cách hàng nghìn cho tiền tệ
USE_L10N = False 
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = '.'
NUMBER_GROUPING = 3

# Cấu hình đường dẫn cho file tĩnh (CSS/JS) và file tải lên (Media/Ảnh)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'