# Generated by Django 6.0 on 2025-12-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_product_delete_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'danh mục', 'verbose_name_plural': 'N1-JEWELRY - Danh mục Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'sản phẩm', 'verbose_name_plural': 'N1-JEWELRY - Sản phẩm'},
        ),
    ]
