# Generated by Django 6.0 on 2026-01-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name_plural': 'N1-JEWELRY - Đơn hàng'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='gemstone',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_weight',
        ),
        migrations.AddField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('cartier', 'Cartier'), ('style', 'Style')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('nu', 'Dành cho Nữ'), ('nam', 'Dành cho Nam'), ('unisex', 'Unisex')], default='unisex', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='meaning',
            field=models.CharField(blank=True, choices=[('tinh-yeu', 'Tình yêu bền chặt'), ('may-man', 'May mắn thu hút'), ('tai-loc', 'Tài lộc dồi dào'), ('thinh-vuong', 'Thịnh vượng phát triển'), ('gan-ket', 'Gắn kết trân trọng')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('nhan', 'Nhẫn'), ('vong', 'Vòng'), ('day-chuyen', 'Dây chuyền')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='purpose',
            field=models.CharField(blank=True, choices=[('du-tiec', 'Dự tiệc'), ('hang-ngay', 'Hằng ngày'), ('cau-hon', 'Cầu hôn'), ('ky-niem', 'Kỷ niệm'), ('qua-tang', 'Quà tặng'), ('sinh-nhat', 'Sinh nhật')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('bac', 'Bạc'), ('vang', 'Vàng'), ('kim-cuong', 'Kim cương')], default='vang', max_length=50),
        ),
    ]
