# Generated by Django 6.0 on 2026-01-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_order_options_remove_product_gemstone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('pnj', 'PNJ'), ('cartier', 'Cartier'), ('style', 'Style')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(default='unisex', help_text='Có thể chọn nhiều, cách nhau bởi dấu phзапy', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='meaning',
            field=models.CharField(blank=True, help_text='Có thể chọn nhiều, cách nhau bởi dấu phẩy', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='purpose',
            field=models.CharField(blank=True, help_text='Có thể chọn nhiều, cách nhau bởi dấu phẩy', max_length=200, null=True),
        ),
    ]
