# Generated by Django 6.0 on 2026-05-18 12:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_brand_alter_product_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên Khách')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Số Điện Thoại')),
                ('member_type', models.CharField(choices=[('vangLai', 'Vãng Lai'), ('thanhVien', 'Thành Viên'), ('vip', 'VIP')], default='vangLai', max_length=20, verbose_name='Loại Thành Viên')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số Dư (₫)')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Khách Hàng',
                'verbose_name_plural': 'Mimi Lê — Khách Hàng',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên Máy')),
                ('machine_type', models.CharField(choices=[('thuong', 'Máy Thường'), ('gaming', 'Máy Gaming'), ('vip', 'Phòng VIP')], default='thuong', max_length=20, verbose_name='Loại Máy')),
                ('status', models.CharField(choices=[('trong', 'Trống'), ('dang_dung', 'Đang Dùng'), ('bao_tri', 'Bảo Trì')], default='trong', max_length=20, verbose_name='Trạng Thái')),
                ('hourly_rate', models.DecimalField(decimal_places=0, default=10000, max_digits=10, verbose_name='Giá/Giờ (₫)')),
                ('has_headset', models.BooleanField(default=True, verbose_name='Có Tai Nghe')),
                ('has_account', models.BooleanField(default=False, verbose_name='Có Tài Khoản Game')),
                ('ram_gb', models.PositiveIntegerField(default=8, verbose_name='RAM (GB)')),
                ('note', models.TextField(blank=True, verbose_name='Ghi Chú')),
            ],
            options={
                'verbose_name': 'Máy Tính',
                'verbose_name_plural': 'Mimi Lê — Máy Tính',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Tên Khách')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('preferred_type', models.CharField(choices=[('thuong', 'Máy Thường'), ('gaming', 'Máy Gaming'), ('vip', 'Phòng VIP')], default='thuong', max_length=20, verbose_name='Loại Máy Muốn')),
                ('arrived_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Giờ Đến')),
                ('planned_minutes', models.PositiveIntegerField(default=60, verbose_name='Dự Kiến Chơi (phút)')),
                ('is_served', models.BooleanField(default=False, verbose_name='Đã Được Phục Vụ')),
            ],
            options={
                'verbose_name': 'Hàng Chờ',
                'verbose_name_plural': 'Mimi Lê — Hàng Chờ',
                'ordering': ['arrived_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên Dịch Vụ')),
                ('category', models.CharField(choices=[('do_uong', 'Đồ Uống'), ('do_an', 'Đồ Ăn'), ('phu_kien', 'Phụ Kiện'), ('khac', 'Khác')], default='do_uong', max_length=20, verbose_name='Loại')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá (₫)')),
                ('stock', models.IntegerField(default=100, verbose_name='Tồn Kho')),
                ('available', models.BooleanField(default=True, verbose_name='Còn Bán')),
            ],
            options={
                'verbose_name': 'Dịch Vụ',
                'verbose_name_plural': 'Mimi Lê — Dịch Vụ',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, verbose_name='Tên Khách (nhanh)')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Giờ Bắt Đầu')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Giờ Kết Thúc')),
                ('used_headset', models.BooleanField(default=False, verbose_name='Dùng Tai Nghe')),
                ('used_account', models.BooleanField(default=False, verbose_name='Dùng Tài Khoản Game')),
                ('used_ram_gb', models.PositiveIntegerField(default=0, verbose_name='RAM Sử Dụng (GB)')),
                ('planned_minutes', models.PositiveIntegerField(default=60, verbose_name='Thời Gian Dự Kiến (phút)')),
                ('total_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng Tiền (₫)')),
                ('paid', models.BooleanField(default=False, verbose_name='Đã Thanh Toán')),
                ('status', models.CharField(choices=[('dang_chay', 'Đang Chạy'), ('hoan_thanh', 'Hoàn Thành'), ('tam_dung', 'Tạm Dừng')], default='dang_chay', max_length=20, verbose_name='Trạng Thái')),
            ],
            options={
                'verbose_name': 'Phiên Chơi',
                'verbose_name_plural': 'Mimi Lê — Phiên Chơi',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SessionService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số Lượng')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Đơn Giá')),
            ],
            options={
                'verbose_name': 'Dịch Vụ Trong Phiên',
                'verbose_name_plural': 'Mimi Lê — Dịch Vụ Trong Phiên',
            },
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='app_product_id_e8d3b3_idx',
        ),
        migrations.AddField(
            model_name='session',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customer', verbose_name='Khách Hàng'),
        ),
        migrations.AddField(
            model_name='session',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.machine', verbose_name='Máy'),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nhân Viên Tạo'),
        ),
        migrations.AddField(
            model_name='sessionservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service', verbose_name='Dịch Vụ'),
        ),
        migrations.AddField(
            model_name='sessionservice',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='app.session', verbose_name='Phiên'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
