# Generated by Django 6.0 on 2026-05-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customer_machine_queue_service_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Giảm Giá (%)'),
        ),
        migrations.AddField(
            model_name='session',
            name='game_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Game / Hoạt Động'),
        ),
        migrations.AddField(
            model_name='session',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mã Khuyến Mãi'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('trong', 'Trống'), ('dang_dung', 'Đang Dùng'), ('bao_tri', 'Bảo Trì'), ('loi', 'Lỗi/Kết Nối'), ('khoa', 'Khóa')], default='trong', max_length=20, verbose_name='Trạng Thái'),
        ),
    ]
