# Generated by Django 6.0 on 2026-05-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_logintoken_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='machine_images/', verbose_name='Ảnh máy'),
        ),
    ]
