# Generated by Django 6.0 on 2026-05-25 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_machine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi Chú'),
        ),
        migrations.AddField(
            model_name='queue',
            name='preferred_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.machine', verbose_name='Máy Cụ Thể (nếu muốn)'),
        ),
    ]
